version: '3'

services:
  app:
    restart: always
    build: .
    command: /usr/bin/supervisord
    volumes:
      - /var/lib/judge/data
    ports:
      - "80:80"
    depends_on:
      - ubuntu
      - postgres
      - redis
  postgres:
    restart: always
    image: onjin/alpine-postgres:9.6
  redis:
    restart: always
    image: redis
  ubuntu:
    build:
      context: deploy/ubuntu
