# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20170413_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('source_path', models.FilePathField(path='/home/nsapunov/Repos/self/edujudge/app/user_sources')),
                ('is_error', models.BooleanField(default=False)),
                ('verdict', models.TextField(default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task')),
                ('test', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.RemoveField(
            model_name='check',
            name='task',
        ),
        migrations.RemoveField(
            model_name='check',
            name='test',
        ),
        migrations.RemoveField(
            model_name='check',
            name='user',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
