# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170413_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='testnum',
            field=models.SmallIntegerField(default=0),
        ),
    ]
