# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170416_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
    ]
