# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20170418_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
