# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_generator_path',
            field=models.FilePathField(blank=True, null=True, path='/var/lib/judge/data/test_generators'),
        ),
    ]
