# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_task_test_generator_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='error_line',
            field=models.IntegerField(default=-1),
        ),
    ]
