# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_solution_error_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_checker_path',
            field=models.FilePathField(blank=True, null=True, path='/var/lib/judge/data/test_checkers'),
        ),
    ]
