# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test_checker_path',
            field=models.FilePathField(default=None, null=True, path='/var/lib/judge/data/test_checkers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_generator_path',
            field=models.FilePathField(default=None, null=True, path='/var/lib/judge/data/test_generators'),
        ),
    ]
