# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-30 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190225_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
