# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.AddField(
            model_name='notification',
            name='html',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
