# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190213_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('co', 'comment')], max_length=2),
        ),
    ]
