# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-31 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190225_2153'),
        ('api', '0022_auto_20190214_0030'),
    ]

    operations = [
    ]
