# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-31 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20200131_2320'),
        ('api', '0021_task_show'),
    ]

    operations = [
    ]
